---
# Get project from github
- name: Get Back from Github
  git:
    repo: https://{{GITHUB_TOKEN}}@github.com/TonyoCallimoutou/Wedding_Moment_Back.git
    dest: /home/tonyo/projet/Wedding_Moment_Back

- name: Get Front from Github
  git:
    repo: https://{{GITHUB_TOKEN}}@github.com/TonyoCallimoutou/Wedding_Moment_Front.git
    dest: /home/tonyo/projet/Wedding_Moment_Front

# Copy file
- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /home/tonyo/projet/docker
    state: directory
    mode: '0755'

- name: Copy docker-compose.yml
  copy:
    src: ../../../docker-compose.yml
    dest: /home/tonyo/projet/docker/docker-compose.yml

- name: Copy .env for Docker compose
  copy:
    src: ../../../.env
    dest: /home/tonyo/projet/docker/.env

- name: Copy nginc.conf for NGINX
  copy:
    src: ../../../nginx.conf
    dest: /home/tonyo/projet/docker/nginx.conf

- name: Copy .env for Front
  copy:
    src: ../../../.env
    dest: /home/tonyo/projet/Wedding_Moment_Front/.env

- name: Copy .env for Back
  copy:
    src: ../../../.env
    dest: /home/tonyo/projet/Wedding_Moment_Back/.env

- name: Copy env.config.sh for dock
  copy:
    src: ../../../env.config.sh
    dest: /home/tonyo/projet/docker/env.config.sh

- name: Copy restart_docker.sh for dock
  copy:
    src: ../../../env.config.sh
    dest: /home/tonyo/projet/docker/restart_docker.sh

- name: Copy stop_docker.sh for dock
  copy:
    src: ../../../env.config.sh
    dest: /home/tonyo/projet/docker/stop_docker.sh


# RUN Docker
#- name: Run docker-compose
#  shell: 
#    cmd: "sudo docker-compose up -d"
#    chdir: /home/tonyo/projet/docker