---
# Get project from github
- name: Get Back from Github
  git:
    repo: https://{{GITHUB_TOKEN}}@github.com/{{GITHUB_USERNAME}}/{{NAME_BACK_REPO_GIT}}.git
    dest: /home/vagrant/projet/{{NAME_BACK_REPO_GIT}}
    version: DevOps

- name: Get Front from Github
  git:
    repo: https://{{GITHUB_TOKEN}}@github.com/{{GITHUB_USERNAME}}/{{NAME_FRONT_REPO_GIT}}.git
    dest: /home/vagrant/projet/{{NAME_FRONT_REPO_GIT}}
    version: DevOps

# Copy file
- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /home/vagrant/projet/docker
    state: directory
    mode: '0755'

- name: Copy docker-compose.yml
  copy:
    src: ../../../docker-compose.yml
    dest: /home/vagrant/projet/docker/docker-compose.yml

- name: Copy .env for Docker compose
  copy:
    src: ../../../.env
    dest: /home/vagrant/projet/docker/.env

- name: Copy nginc.conf for NGINX
  copy:
    src: ../../../nginx.conf
    dest: /home/vagrant/projet/docker/nginx.conf

- name: Copy .env for Front
  copy:
    src: ../../../.env
    dest: /home/vagrant/projet/{{NAME_FRONT_REPO_GIT}}/.env

- name: Copy .env for Back
  copy:
    src: ../../../.env
    dest: /home/vagrant/projet/{{NAME_BACK_REPO_GIT}}/.env

# RUN Docker
- name: Run docker-compose
  shell: 
    cmd: "sudo docker-compose up -d"
    chdir: /home/vagrant/projet/docker