---
# Get project from github
- name: Get Back from Github
  copy:
    src: ../../../../Wedding_Moment_Back
    dest: /home/vagrant/projet/code

- name: Get Front from Github
  copy:
    src: ../../../../Wedding_Moment_Front
    dest: /home/vagrant/projet/code

# Copy file
- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /home/vagrant/projet/docker
    state: directory
    mode: '0755'

- name: Copy docker-compose.yml
  copy:
    src: ../../../docker-compose.yml
    dest: /home/vagrant/projet/docker/docker-compose.yml

- name: Copy .env for Docker compose
  copy:
    src: ../../../.env
    dest: /home/vagrant/projet/docker/.env

# RUN Docker
- name: Run docker-compose
  shell: 
    cmd: "sudo docker-compose up -d"
    chdir: /home/vagrant/projet/docker